disabled_rules:
  - identifier_name
  - cyclomatic_complexity
  - notification_center_detachment
  - operator_usage_whitespace
  - orphaned_doc_comment
  - todo
  - trailing_whitespace
  - empty_enum_arguments
  - nesting

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - duplicate_enum_cases
  - empty_collection_literal
  - empty_count
  - empty_string
  - force_unwrapping
  - indentation_width
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_void_return
  - strict_fileprivate
  - switch_case_alignment
  - trailing_closure
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_closure_parameter
  - void_return
  - weak_delegate
  - yoda_condition

file_length:
  - 1000
  - 10000

type_body_length:
  - 500

type_name:
  min_length:
    warning: 1
    error: 0
  max_length: 
    warning: 50
    error: 60

function_parameter_count:
  warning: 6
  error: 15

line_length:
  warning: 130
  error: 2000
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

vertical_whitespace:
  max_empty_lines: 2

force_cast: warning 

empty_count: 
  severity: warning

force_try: warning

large_tuple: 
  warning: 3
  error: 4

shorthand_operator: warning

function_body_length:
  warning: 40
  error: 100